//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoDuong
    {
        public int IdBaoduong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> IdKHBaoDuong { get; set; }
        public string MaMay { get; set; }
        public string TinhTrang { get; set; }
        public string UserName { get; set; }
    
        public virtual KHBaoDuong KHBaoDuong { get; set; }
        public virtual TaiSanCoDinh TaiSanCoDinh { get; set; }
        public virtual Users Users { get; set; }
    }
}
