//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomLkTp
    {
        public int IdLkTp { get; set; }
        public string MaTp { get; set; }
        public string SoHoa { get; set; }
        public string MaMuaHang { get; set; }
        public Nullable<int> HeSo { get; set; }
        public Nullable<bool> DapKhuon { get; set; }
        public Nullable<bool> EpNhua { get; set; }
        public Nullable<bool> Han { get; set; }
        public Nullable<bool> Son { get; set; }
        public Nullable<bool> LapRap { get; set; }
        public string UserName { get; set; }
    
        public virtual BomLk BomLk { get; set; }
        public virtual BomNl BomNl { get; set; }
        public virtual BomTp BomTp { get; set; }
        public virtual Users Users { get; set; }
    }
}
