//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomLk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BomLk()
        {
            this.BomLkTp = new HashSet<BomLkTp>();
            this.DKSanXuat = new HashSet<DKSanXuat>();
            this.EPSanXuat = new HashSet<EPSanXuat>();
            this.HanSanXuat = new HashSet<HanSanXuat>();
            this.DKKiemTra = new HashSet<DKKiemTra>();
            this.EPKiemTra = new HashSet<EPKiemTra>();
            this.KhoLinhKienInputInfo = new HashSet<KhoLinhKienInputInfo>();
            this.KhoLinhKienOutputInfo = new HashSet<KhoLinhKienOutputInfo>();
            this.DKNguyenLieuLK = new HashSet<DKNguyenLieuLK>();
            this.LrNguyenLieuLk = new HashSet<LrNguyenLieuLk>();
            this.EPPhatLieu = new HashSet<EPPhatLieu>();
            this.SonSanXuat = new HashSet<SonSanXuat>();
        }
    
        public string SoHoa { get; set; }
        public string DisplayName { get; set; }
        public string QuyCach { get; set; }
        public string IdU { get; set; }
        public Nullable<bool> DapKhuon { get; set; }
        public Nullable<bool> EpNhua { get; set; }
        public Nullable<bool> Han { get; set; }
        public Nullable<bool> Son { get; set; }
        public Nullable<bool> LapRap { get; set; }
        public string UserName { get; set; }
    
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BomLkTp> BomLkTp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKSanXuat> DKSanXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPSanXuat> EPSanXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanSanXuat> HanSanXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKKiemTra> DKKiemTra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPKiemTra> EPKiemTra { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoLinhKienInputInfo> KhoLinhKienInputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoLinhKienOutputInfo> KhoLinhKienOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKNguyenLieuLK> DKNguyenLieuLK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LrNguyenLieuLk> LrNguyenLieuLk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPPhatLieu> EPPhatLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SonSanXuat> SonSanXuat { get; set; }
    }
}
