//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomNl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BomNl()
        {
            this.BomLkTp = new HashSet<BomLkTp>();
            this.DKNguyenLieu = new HashSet<DKNguyenLieu>();
            this.EPNguyenLieu = new HashSet<EPNguyenLieu>();
            this.HanNguyenLieu = new HashSet<HanNguyenLieu>();
            this.LrNguyenLieu = new HashSet<LrNguyenLieu>();
            this.OutputInfo = new HashSet<OutputInfo>();
            this.SonNguyenLieu = new HashSet<SonNguyenLieu>();
            this.KhoNguyenLieuOutputInfo = new HashSet<KhoNguyenLieuOutputInfo>();
            this.KhoNguyenLieuInputInfo = new HashSet<KhoNguyenLieuInputInfo>();
        }
    
        public string MaMuaHang { get; set; }
        public string DisplayName { get; set; }
        public string ChatLieu { get; set; }
        public string QuyCach { get; set; }
        public string IdU { get; set; }
        public string PhanLoaiBom { get; set; }
        public Nullable<bool> DapKhuon { get; set; }
        public Nullable<bool> EpNhua { get; set; }
        public Nullable<bool> Han { get; set; }
        public Nullable<bool> Son { get; set; }
        public Nullable<bool> LapRap { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BomLkTp> BomLkTp { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKNguyenLieu> DKNguyenLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPNguyenLieu> EPNguyenLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanNguyenLieu> HanNguyenLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LrNguyenLieu> LrNguyenLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SonNguyenLieu> SonNguyenLieu { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoNguyenLieuOutputInfo> KhoNguyenLieuOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoNguyenLieuInputInfo> KhoNguyenLieuInputInfo { get; set; }
    }
}
