//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DKKiemTra
    {
        public int IdSxCheck { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string CaLv { get; set; }
        public string MaMay { get; set; }
        public string NhanVien { get; set; }
        public string SoHoa { get; set; }
        public Nullable<double> Kichthuoc1 { get; set; }
        public Nullable<double> Kichthuoc2 { get; set; }
        public Nullable<double> Kichthuoc3 { get; set; }
        public Nullable<double> Kichthuoc4 { get; set; }
        public Nullable<double> Kichthuoc5 { get; set; }
        public Nullable<double> Kichthuoc6 { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public string MaPhieu { get; set; }
        public string UserName { get; set; }
    
        public virtual BomLk BomLk { get; set; }
        public virtual TaiSanCoDinh TaiSanCoDinh { get; set; }
        public virtual Users Users { get; set; }
    }
}
