//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DKNguyenLieu
    {
        public int IdNlDk { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaMuaHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NhapXuat { get; set; }
        public string IdU { get; set; }
        public string UserName { get; set; }
        public string SoLo { get; set; }
    
        public virtual BomNl BomNl { get; set; }
        public virtual Users Users { get; set; }
        public virtual DonHangTp DonHangTp { get; set; }
    }
}
