//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangTp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangTp()
        {
            this.LrSanXuat = new HashSet<LrSanXuat>();
            this.XuatTp = new HashSet<XuatTp>();
            this.DKSanXuat = new HashSet<DKSanXuat>();
            this.KhoLinhKienOutputInfo = new HashSet<KhoLinhKienOutputInfo>();
            this.KhoNguyenLieuOutputInfo = new HashSet<KhoNguyenLieuOutputInfo>();
            this.DKNguyenLieu = new HashSet<DKNguyenLieu>();
            this.LrNguyenLieu = new HashSet<LrNguyenLieu>();
            this.DKNguyenLieuLK = new HashSet<DKNguyenLieuLK>();
            this.KhoThanhPhamInputInfo = new HashSet<KhoThanhPhamInputInfo>();
            this.KhoThanhPhamInputInfo1 = new HashSet<KhoThanhPhamInputInfo>();
            this.LrNguyenLieuLk = new HashSet<LrNguyenLieuLk>();
            this.KhoThanhPhamOutputInfo = new HashSet<KhoThanhPhamOutputInfo>();
            this.KhoThanhPhamOutputInfo1 = new HashSet<KhoThanhPhamOutputInfo>();
            this.SonSanXuat = new HashSet<SonSanXuat>();
        }
    
        public string SoLo { get; set; }
        public Nullable<System.DateTime> NgayLenDon { get; set; }
        public string MaTp { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string IdU { get; set; }
        public string TinhTrang { get; set; }
        public string UserName { get; set; }
    
        public virtual BomTp BomTp { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LrSanXuat> LrSanXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatTp> XuatTp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKSanXuat> DKSanXuat { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoLinhKienOutputInfo> KhoLinhKienOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoNguyenLieuOutputInfo> KhoNguyenLieuOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKNguyenLieu> DKNguyenLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LrNguyenLieu> LrNguyenLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKNguyenLieuLK> DKNguyenLieuLK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoThanhPhamInputInfo> KhoThanhPhamInputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoThanhPhamInputInfo> KhoThanhPhamInputInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LrNguyenLieuLk> LrNguyenLieuLk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoThanhPhamOutputInfo> KhoThanhPhamOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoThanhPhamOutputInfo> KhoThanhPhamOutputInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SonSanXuat> SonSanXuat { get; set; }
    }
}
