//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPKiemTra
    {
        public int IdEnKiemTra { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string CaLv { get; set; }
        public string MaMay { get; set; }
        public string NhanVien { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public string SoHoa { get; set; }
        public Nullable<bool> KhongHutNhua { get; set; }
        public Nullable<bool> DongMau { get; set; }
        public Nullable<bool> Bavia { get; set; }
        public Nullable<bool> GonSong { get; set; }
        public Nullable<double> DuongKinh { get; set; }
        public Nullable<double> TrucGiua { get; set; }
        public Nullable<bool> ThaoLap { get; set; }
        public Nullable<double> CanNang { get; set; }
        public string UserName { get; set; }
    
        public virtual BomLk BomLk { get; set; }
        public virtual TaiSanCoDinh TaiSanCoDinh { get; set; }
        public virtual Users Users { get; set; }
    }
}
