//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPNhietDo
    {
        public int IdEnNhietDo { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string CaLv { get; set; }
        public string MaMay { get; set; }
        public string NhanVien { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public string SoHoa { get; set; }
        public Nullable<System.TimeSpan> TimeWrite { get; set; }
        public Nullable<int> NhietDo1 { get; set; }
        public Nullable<int> NhietDo2 { get; set; }
        public Nullable<int> NhietDo3 { get; set; }
        public Nullable<int> NhietDo4 { get; set; }
        public Nullable<int> NhietDo5 { get; set; }
        public Nullable<int> NhietDoSay { get; set; }
        public Nullable<int> VPhunKeoMin { get; set; }
        public Nullable<int> VPhunKeoMax { get; set; }
        public Nullable<int> PPhunKeoMin { get; set; }
        public Nullable<int> PPhunKeoMax { get; set; }
        public Nullable<int> TimeBom { get; set; }
        public string UserName { get; set; }
    
        public virtual TaiSanCoDinh TaiSanCoDinh { get; set; }
        public virtual Users Users { get; set; }
    }
}
