//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPSanXuat
    {
        public int IdSxEn { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaMay { get; set; }
        public string NhanVien { get; set; }
        public string SoHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string IdU { get; set; }
        public Nullable<int> Phe { get; set; }
        public string NguyenNhan { get; set; }
        public Nullable<System.TimeSpan> hourstart { get; set; }
        public Nullable<System.TimeSpan> hourend { get; set; }
        public string CaLv { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<int> SoLuongMay { get; set; }
        public Nullable<int> SoLuongChuKy { get; set; }
        public Nullable<int> TimeChuKy { get; set; }
        public string UserName { get; set; }
    
        public virtual BomLk BomLk { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual TaiSanCoDinh TaiSanCoDinh { get; set; }
        public virtual Users Users { get; set; }
    }
}
