//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPThemNL
    {
        public int IdEnThemNL { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string CaLv { get; set; }
        public string MaMay { get; set; }
        public string NhanVien { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public string MaNVL { get; set; }
        public Nullable<int> KhoiLuongMoi { get; set; }
        public Nullable<int> KhoiLuongCu { get; set; }
        public string GhiChu { get; set; }
        public string UserName { get; set; }
    
        public virtual TaiSanCoDinh TaiSanCoDinh { get; set; }
        public virtual Users Users { get; set; }
    }
}
