//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputInfo
    {
        public int IdInput { get; set; }
        public string IdPhieuNhap { get; set; }
        public string MaMuaHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string IdU { get; set; }
        public string MaKho { get; set; }
    
        public virtual BomNl BomNl { get; set; }
        public virtual Inputt Inputt { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
