//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kho()
        {
            this.OutputInfo = new HashSet<OutputInfo>();
            this.XuatTp = new HashSet<XuatTp>();
            this.KhoLinhKienInputInfo = new HashSet<KhoLinhKienInputInfo>();
            this.KhoLinhKienOutputInfo = new HashSet<KhoLinhKienOutputInfo>();
            this.KhoNgoaiSXOutputInfo = new HashSet<KhoNgoaiSXOutputInfo>();
            this.KhoNgoaiSXInputInfo = new HashSet<KhoNgoaiSXInputInfo>();
            this.KhoNguyenLieuOutputInfo = new HashSet<KhoNguyenLieuOutputInfo>();
            this.KhoNguyenLieuInputInfo = new HashSet<KhoNguyenLieuInputInfo>();
            this.KhoThanhPhamInputInfo = new HashSet<KhoThanhPhamInputInfo>();
            this.KhoThanhPhamOutputInfo = new HashSet<KhoThanhPhamOutputInfo>();
        }
    
        public string MaKho { get; set; }
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public string MaBp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatTp> XuatTp { get; set; }
        public virtual BoPhan BoPhan { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoLinhKienInputInfo> KhoLinhKienInputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoLinhKienOutputInfo> KhoLinhKienOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoNgoaiSXOutputInfo> KhoNgoaiSXOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoNgoaiSXInputInfo> KhoNgoaiSXInputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoNguyenLieuOutputInfo> KhoNguyenLieuOutputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoNguyenLieuInputInfo> KhoNguyenLieuInputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoThanhPhamInputInfo> KhoThanhPhamInputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoThanhPhamOutputInfo> KhoThanhPhamOutputInfo { get; set; }
    }
}
