//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoThanhPhamOutputInfo
    {
        public int STT { get; set; }
        public string MaPhieu { get; set; }
        public string SoLo1 { get; set; }
        public string MaTp1 { get; set; }
        public int SoLuongNhap1 { get; set; }
        public string IdU1 { get; set; }
        public string SoLo2 { get; set; }
        public string MaTp2 { get; set; }
        public Nullable<int> SoLuongNhap2 { get; set; }
        public string IdU2 { get; set; }
        public Nullable<int> KhoiLuongKien { get; set; }
        public string MaKho { get; set; }
        public string GhiChu { get; set; }
        public string ViTri { get; set; }
        public string UserName { get; set; }
        public string QRcode { get; set; }
        public string DisplayName1 { get; set; }
        public string DisplayName2 { get; set; }
    
        public virtual BomTp BomTp { get; set; }
        public virtual BomTp BomTp1 { get; set; }
        public virtual DonHangTp DonHangTp { get; set; }
        public virtual DonHangTp DonHangTp1 { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual KhoThanhPhamOutput KhoThanhPhamOutput { get; set; }
        public virtual Users Users { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
