//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanSu
    {
        public string MSNV { get; set; }
        public string NhanVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string Phone { get; set; }
        public string MaBp { get; set; }
        public int IdNhanSu { get; set; }
        public byte[] HinhAnh { get; set; }
        public string ChucVu { get; set; }
        public string IDMayChamCong { get; set; }
        public string GioiTinh { get; set; }
        public string UserName { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual BoPhan BoPhan { get; set; }
        public virtual Users Users { get; set; }
    }
}
