//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SonKiemTra
    {
        public int IdSonKiemTra { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string CaLv { get; set; }
        public string NhanVien { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public Nullable<double> NongDoTayDau1 { get; set; }
        public Nullable<double> NhietDoTayDau1 { get; set; }
        public Nullable<double> NongDoTayDau2 { get; set; }
        public Nullable<double> NhietDoTayDau2 { get; set; }
        public Nullable<double> NongDoTaoMang { get; set; }
        public Nullable<double> NhietDoTaoMang { get; set; }
        public Nullable<double> pHTaoMang { get; set; }
        public Nullable<double> NongDoSon { get; set; }
        public Nullable<double> pHSon { get; set; }
        public Nullable<double> NhietDoSon { get; set; }
        public Nullable<double> KhucXaBe { get; set; }
        public Nullable<double> DoDanDien { get; set; }
        public Nullable<double> NongDoDungMoi { get; set; }
        public string UserName { get; set; }
    }
}
