//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw3_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatTp
    {
        public int IdOutput { get; set; }
        public Nullable<System.DateTime> DateXuat { get; set; }
        public string MaTp { get; set; }
        public string SoLo { get; set; }
        public Nullable<int> SoluongXuat { get; set; }
        public string IdU { get; set; }
        public string MaKho { get; set; }
        public string UserName { get; set; }
    
        public virtual BomTp BomTp { get; set; }
        public virtual DonHangTp DonHangTp { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Users Users { get; set; }
    }
}
